[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
surrealdb="1.0.0-beta.9"
tokio={version="1",features=["full"]}
anyhow="1"